# Generated by Django 5.1.3 on 2024-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponiveis_tabela_vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.IntegerField(default=0)),
                ('empresa', models.IntegerField(default=0)),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('obra', models.CharField(default='', max_length=10)),
                ('unidade', models.CharField(default='', max_length=10)),
                ('tipo', models.CharField(default='', max_length=60)),
                ('cod_tipologia', models.IntegerField(default=0)),
                ('tipologia', models.CharField(default='', max_length=60)),
                ('status', models.CharField(default='', max_length=100)),
                ('data_insercao', models.DateTimeField()),
            ],
        ),
    ]
