# Generated by Django 5.1.3 on 2024-12-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponiveis_tabela_vendas',
            name='data_insercao',
        ),
    ]
