# Generated by Django 5.1.3 on 2024-12-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_disponiveis_tabela_vendas_unidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponiveis_tabela_vendas',
            old_name='empresa',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='disponiveis_tabela_vendas',
            old_name='nome_fantasia',
            new_name='NomeFantasia',
        ),
        migrations.RenameField(
            model_name='disponiveis_tabela_vendas',
            old_name='obra',
            new_name='Obra',
        ),
        migrations.RenameField(
            model_name='disponiveis_tabela_vendas',
            old_name='produto',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='disponiveis_tabela_vendas',
            old_name='unidade',
            new_name='Unidade',
        ),
    ]
