# Generated by Django 5.1.3 on 2024-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_empresa_disponiveis_tabela_vendas_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponiveis_tabela_vendas',
            name='Empresa',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='disponiveis_tabela_vendas',
            name='Produto',
            field=models.CharField(max_length=6),
        ),
    ]
