# Generated by Django 5.1.3 on 2024-12-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_produto_disponiveis_tabela_vendas_produt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponiveis_tabela_vendas',
            old_name='Produt',
            new_name='Produto',
        ),
    ]
