# Generated by Django 5.1.3 on 2024-11-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalCorretoresHypno', '0004_cadastro_tabeladevendas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='TabelaDeVendas',
        ),
    ]
